version: '3.8'
services:
  php-apache:
    build: ./php-apache
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html:z
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql   # Volumen persistente

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:   # Volumen nombrado para persistencia
